# Config file for automatic testing at travis-ci.org
language: python
python:
    - "3.6"

env:
    - PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so

addons:
    apt:
        packages:
            - gfortran
            - openmpi-bin
            - libopenmpi-dev
            - python3-yaml

# command to install dependencies
install:
    - pip install flake8 coveralls
    - python setup.py install

before_script:
    # Test for pep-compliance
    - flake8 high_dimensional_sampling tests

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls
