# Config file for automatic testing at travis-ci.org
language: python
python:
    - "3.6"

addons:
    apt:
        packages:
            - gfortran
            - openmpi-bin
            - libopenmpi-dev

# command to install dependencies
install:
    - pip install flake8 coveralls
    - python3.5 -m pip install pyyaml --user
    - python setup.py install

before_script:
    # Test for pep-compliance
    - flake8 high_dimensional_sampling tests

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls
