# Config file for automatic testing at travis-ci.org
language: python
python:
    - "3.6"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install flake8

before_script:
    # Test for pep-compliance
    - flake8 high_dimensional_sampling tests


# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls