# Config file for automatic testing at travis-ci.org
language: python
python:
    - "3.6"

addons:
    apt:
        packages:
            - gfortran

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install flake8
    - pip install coveralls
    - pip install pyscannerbit --install-option="cmake_args=['-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so']"
    - python setup.py install

before_script:
    # Test for pep-compliance
    - flake8 high_dimensional_sampling tests

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls
